# Generated by Django 4.2.2 on 2023-07-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('phone', models.CharField(max_length=13, verbose_name='電話番号')),
                ('product', models.CharField(max_length=50, verbose_name='商品の名前')),
                ('jan', models.CharField(max_length=15, verbose_name='janコード')),
                ('staff', models.CharField(max_length=10, verbose_name='担当者')),
                ('setcardID', models.CharField(max_length=10, verbose_name='カードID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='予約日')),
                ('memo', models.TextField(blank=True, max_length=300, null=True, verbose_name='備考')),
            ],
            options={
                'verbose_name': 'アイテム',
                'verbose_name_plural': 'アイテム',
            },
        ),
    ]
